theme: jekyll-theme-minimal
title: Clint P. George
twitter_username: clintpgeorge
github_username: clintpgeorge

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
